# References:
# - https://github.com/confluentinc/demo-scene/blob/master/connect-jdbc/docker-compose.yml

version: '3.7'

services:

  sqlserver:
    build: ./images/sqlserver
    container_name: sqlserver
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'BBk_.6WA!k3e'
      MSSQL_AGENT_ENABLED: 'true'
    networks:
      - cnet

  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    networks:
      - cnet

  kafka:
    image: confluentinc/cp-kafka:5.3.0
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    ports:
      # Exposes 9092 for external connections to the broker
      # Use kafka:29092 for connections internal on the docker network
      # See https://rmoff.net/2018/08/02/kafka-listeners-explained/ for details
      - 9092:9092
    networks:
      - cnet

  debezium-connect:
    image: debezium/connect:0.10
    container_name: debezium-connect
    depends_on:
      - kafka
      - sqlserver
    environment:
      BOOTSTRAP_SERVERS: kafka:29092
      GROUP_ID: poc
      CONFIG_STORAGE_TOPIC: poc-config
      OFFSET_STORAGE_TOPIC: poc-offset
      STATUS_STORAGE_TOPIC: poc-status
    ports:
      - 8083:8083
    networks:
      - cnet

networks:
  cnet:
