# References:
# - https://github.com/confluentinc/demo-scene/blob/master/connect-jdbc/docker-compose.yml

version: '3.7'

services:

  sqlserver:
    build: ./images/sqlserver
    container_name: sqlserver
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'BBk_.6WA!k3e'
    networks:
      - cnet

  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    networks:
      - cnet

  kafka:
    image: confluentinc/cp-kafka:5.3.0
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    ports:
      # Exposes 9092 for external connections to the broker
      # Use kafka:29092 for connections internal on the docker network
      # See https://rmoff.net/2018/08/02/kafka-listeners-explained/ for details
      - 9092:9092
    networks:
      - cnet

  kafka_connect:
    image: confluentinc/cp-kafka-connect:5.3.0
    container_name: kafka-connect
    depends_on:
      - kafka
      - sqlserver
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka:29092
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: poc
      CONNECT_CONFIG_STORAGE_TOPIC: poc-config
      CONNECT_OFFSET_STORAGE_TOPIC: poc-offset
      CONNECT_STATUS_STORAGE_TOPIC: poc-status
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_REST_ADVERTISED_HOST_NAME: kafka_connect
      CONNECT_PLUGIN_PATH: /usr/share/java
    ports:
      - 8083:8083
    networks:
      - cnet
    command:
      - /bin/bash
      - -c
      - |
        # Download SQL Server
        cd /usr/share/java/kafka-connect-jdbc
        curl http://central.maven.org/maven2/com/microsoft/sqlserver/mssql-jdbc/7.0.0.jre8/mssql-jdbc-7.0.0.jre8.jar \
          --output mssql-jdbc-7.0.0.jre8.jar

        # Launch Kafka Connect
        sleep infinity &
        /etc/confluent/docker/run

networks:
  cnet:
